;!knitout-2
;;Carriers: 1 2 3 4 5 6 7 8 9 10
x-stitch-number 67
inhook 1
tuck - f62 1
tuck - f58 1
tuck - f54 1
tuck + f56 1
tuck + f60 1
releasehook 1
x-stitch-number 67
knit - b63 1
knit - b59 1
knit - b55 1
knit - b51 1
knit - b47 1
knit - b43 1
knit - b39 1
knit - b35 1
knit - b31 1
knit - b27 1
knit - b23 1
knit - b19 1
knit - b15 1
knit - b11 1
knit - b7 1
knit - b3 1
knit + f0 1
knit + f4 1
knit + f8 1
knit + f12 1
knit + f16 1
knit + f20 1
knit + f24 1
knit + f28 1
knit + f32 1
knit + f36 1
knit + f40 1
knit + f44 1
knit + f48 1
knit + f52 1
knit + f56 1
knit + f60 1
knit - b61 1
knit - b57 1
knit - b53 1
knit - b49 1
knit - b45 1
knit - b41 1
knit - b37 1
knit - b33 1
knit - b29 1
knit - b25 1
knit - b21 1
knit - b17 1
knit - b13 1
knit - b9 1
knit - b5 1
knit - b1 1
knit + f2 1
knit + f6 1
knit + f10 1
knit + f14 1
knit + f18 1
knit + f22 1
knit + f26 1
knit + f30 1
knit + f34 1
knit + f38 1
knit + f42 1
knit + f46 1
knit + f50 1
knit + f54 1
knit + f58 1
knit + f62 1
x-stitch-number 78
knit - b63 1
knit - b61 1
knit - b59 1
knit - b57 1
knit - b55 1
knit - b53 1
knit - b51 1
knit - b49 1
knit - b47 1
knit - b45 1
knit - b43 1
knit - b41 1
knit - b39 1
knit - b37 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
knit - b17 1
knit - b15 1
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit + f36 1
knit + f38 1
knit + f40 1
knit + f42 1
knit + f44 1
knit + f46 1
knit + f48 1
knit + f50 1
knit + f52 1
knit + f54 1
knit + f56 1
knit + f58 1
knit + f60 1
knit + f62 1
knit - b63 1
knit - b61 1
knit - b59 1
knit - b57 1
knit - b55 1
knit - b53 1
knit - b51 1
knit - b49 1
knit - b47 1
knit - b45 1
knit - b43 1
knit - b41 1
knit - b39 1
knit - b37 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
knit - b17 1
knit - b15 1
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit + f36 1
knit + f38 1
knit + f40 1
knit + f42 1
knit + f44 1
knit + f46 1
knit + f48 1
knit + f50 1
knit + f52 1
knit + f54 1
knit + f56 1
knit + f58 1
knit + f60 1
knit + f62 1
knit - b63 1
knit - b61 1
knit - b59 1
knit - b57 1
knit - b55 1
knit - b53 1
knit - b51 1
knit - b49 1
knit - b47 1
knit - b45 1
knit - b43 1
knit - b41 1
knit - b39 1
knit - b37 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
knit - b17 1
knit - b15 1
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit + f36 1
knit + f38 1
knit + f40 1
knit + f42 1
knit + f44 1
knit + f46 1
knit + f48 1
knit + f50 1
knit + f52 1
knit + f54 1
knit + f56 1
knit + f58 1
knit + f60 1
knit + f62 1
knit - b63 1
knit - b61 1
knit - b59 1
knit - b57 1
knit - b55 1
knit - b53 1
knit - b51 1
knit - b49 1
knit - b47 1
knit - b45 1
knit - b43 1
knit - b41 1
knit - b39 1
knit - b37 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
knit - b17 1
knit - b15 1
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit + f36 1
knit + f38 1
knit + f40 1
knit + f42 1
knit + f44 1
knit + f46 1
knit + f48 1
knit + f50 1
knit + f52 1
knit + f54 1
knit + f56 1
knit + f58 1
knit + f60 1
knit + f62 1
knit - b63 1
knit - b61 1
knit - b59 1
knit - b57 1
knit - b55 1
knit - b53 1
knit - b51 1
knit - b49 1
knit - b47 1
knit - b45 1
knit - b43 1
knit - b41 1
knit - b39 1
knit - b37 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
knit - b17 1
knit - b15 1
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit + f36 1
knit + f38 1
knit + f40 1
knit + f42 1
knit + f44 1
knit + f46 1
knit + f48 1
knit + f50 1
knit + f52 1
knit + f54 1
knit + f56 1
knit + f58 1
knit + f60 1
knit + f62 1
knit - b63 1
knit - b61 1
knit - b59 1
knit - b57 1
knit - b55 1
knit - b53 1
knit - b51 1
knit - b49 1
knit - b47 1
knit - b45 1
knit - b43 1
knit - b41 1
knit - b39 1
knit - b37 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
knit - b17 1
knit - b15 1
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit + f36 1
knit + f38 1
knit + f40 1
knit + f42 1
knit + f44 1
knit + f46 1
knit + f48 1
knit + f50 1
knit + f52 1
knit + f54 1
knit + f56 1
knit + f58 1
knit + f60 1
knit + f62 1
knit - b63 1
knit - b61 1
knit - b59 1
knit - b57 1
knit - b55 1
knit - b53 1
knit - b51 1
knit - b49 1
knit - b47 1
knit - b45 1
knit - b43 1
knit - b41 1
knit - b39 1
knit - b37 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
knit - b17 1
knit - b15 1
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit + f36 1
knit + f38 1
knit + f40 1
knit + f42 1
knit + f44 1
knit + f46 1
knit + f48 1
knit + f50 1
knit + f52 1
knit + f54 1
knit + f56 1
knit + f58 1
knit + f60 1
knit + f62 1
knit - b63 1
knit - b61 1
knit - b59 1
knit - b57 1
knit - b55 1
knit - b53 1
knit - b51 1
knit - b49 1
knit - b47 1
knit - b45 1
knit - b43 1
knit - b41 1
knit - b39 1
knit - b37 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
knit - b17 1
knit - b15 1
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit + f36 1
knit + f38 1
knit + f40 1
knit + f42 1
knit + f44 1
knit + f46 1
knit + f48 1
knit + f50 1
knit + f52 1
knit + f54 1
knit + f56 1
knit + f58 1
knit + f60 1
knit + f62 1
knit - b63 1
knit - b61 1
knit - b59 1
knit - b57 1
knit - b55 1
knit - b53 1
knit - b51 1
knit - b49 1
knit - b47 1
knit - b45 1
knit - b43 1
knit - b41 1
knit - b39 1
knit - b37 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
knit - b17 1
knit - b15 1
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit + f36 1
knit + f38 1
knit + f40 1
knit + f42 1
knit + f44 1
knit + f46 1
knit + f48 1
knit + f50 1
knit + f52 1
knit + f54 1
knit + f56 1
knit + f58 1
knit + f60 1
knit + f62 1
knit - b63 1
knit - b61 1
knit - b59 1
knit - b57 1
knit - b55 1
knit - b53 1
knit - b51 1
knit - b49 1
knit - b47 1
knit - b45 1
knit - b43 1
knit - b41 1
knit - b39 1
knit - b37 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
knit - b17 1
knit - b15 1
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit + f36 1
knit + f38 1
knit + f40 1
knit + f42 1
knit + f44 1
knit + f46 1
knit + f48 1
knit + f50 1
knit + f52 1
knit + f54 1
knit + f56 1
knit + f58 1
knit + f60 1
knit + f62 1
knit - b63 1
knit - b61 1
knit - b59 1
knit - b57 1
knit - b55 1
knit - b53 1
knit - b51 1
knit - b49 1
knit - b47 1
knit - b45 1
knit - b43 1
knit - b41 1
knit - b39 1
knit - b37 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
knit - b17 1
knit - b15 1
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
x-stitch-number 67
knit + f36 1
knit + f40 1
knit + f44 1
knit + f48 1
knit + f52 1
knit + f56 1
knit + f60 1
knit - b63 1
knit - b59 1
knit - b55 1
knit - b51 1
knit - b47 1
knit - b43 1
knit - b39 1
knit - b35 1
knit - b31 1
knit - b27 1
knit - b23 1
knit - b19 1
knit - b15 1
knit - b11 1
knit - b7 1
knit - b3 1
knit + f0 1
knit + f4 1
knit + f8 1
knit + f12 1
knit + f16 1
knit + f20 1
knit + f24 1
knit + f28 1
knit + f32 1
knit + f38 1
knit + f42 1
knit + f46 1
knit + f50 1
knit + f54 1
knit + f58 1
knit + f62 1
knit - b61 1
knit - b57 1
knit - b53 1
knit - b49 1
knit - b45 1
knit - b41 1
knit - b37 1
knit - b33 1
knit - b29 1
knit - b25 1
knit - b21 1
knit - b17 1
knit - b13 1
knit - b9 1
knit - b5 1
knit - b1 1
knit + f2 1
knit + f6 1
knit + f10 1
knit + f14 1
knit + f18 1
knit + f22 1
knit + f26 1
knit + f30 1
knit + f34 1
x-stitch-number 78
knit + f36 1
knit + f38 1
knit + f40 1
knit + f42 1
knit + f44 1
knit + f46 1
knit + f48 1
knit + f50 1
knit + f52 1
knit + f54 1
knit + f56 1
knit + f58 1
knit + f60 1
knit + f62 1
knit - b63 1
knit - b61 1
knit - b59 1
knit - b57 1
knit - b55 1
knit - b53 1
knit - b51 1
knit - b49 1
knit - b47 1
knit - b45 1
knit - b43 1
knit - b41 1
knit - b39 1
knit - b37 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
knit - b17 1
knit - b15 1
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit + f36 1
knit + f38 1
knit + f40 1
knit + f42 1
knit + f44 1
knit + f46 1
knit + f48 1
knit + f50 1
knit + f52 1
knit + f54 1
knit + f56 1
knit + f58 1
knit + f60 1
knit + f62 1
knit - b63 1
knit - b61 1
knit - b59 1
knit - b57 1
knit - b55 1
knit - b53 1
knit - b51 1
knit - b49 1
knit - b47 1
knit - b45 1
knit - b43 1
knit - b41 1
knit - b39 1
knit - b37 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
knit - b17 1
knit - b15 1
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit + f36 1
knit + f38 1
knit + f40 1
knit + f42 1
knit + f44 1
knit + f46 1
knit + f48 1
knit + f50 1
knit + f52 1
knit + f54 1
knit + f56 1
knit + f58 1
knit + f60 1
knit + f62 1
knit - b63 1
knit - b61 1
knit - b59 1
knit - b57 1
knit - b55 1
knit - b53 1
knit - b51 1
knit - b49 1
knit - b47 1
knit - b45 1
knit - b43 1
knit - b41 1
knit - b39 1
knit - b37 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
knit - b17 1
knit - b15 1
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
xfer f0 b0
xfer f2 b2
xfer f4 b4
xfer f6 b6
xfer f8 b8
xfer f10 b10
xfer f12 b12
xfer f14 b14
xfer f16 b16
xfer f18 b18
xfer f20 b20
xfer f22 b22
xfer f24 b24
xfer f26 b26
xfer f28 b28
xfer f30 b30
xfer f32 b32
xfer f34 b34
xfer f36 b36
xfer f38 b38
xfer f40 b40
xfer f42 b42
xfer f44 b44
xfer f46 b46
xfer f48 b48
xfer f50 b50
xfer f52 b52
xfer f54 b54
xfer f56 b56
xfer f58 b58
xfer f60 b60
rack 2
xfer f62 b60
rack 0
xfer b0 f0
xfer b2 f2
xfer b4 f4
xfer b6 f6
xfer b8 f8
xfer b10 f10
xfer b12 f12
xfer b14 f14
xfer b16 f16
xfer b18 f18
xfer b20 f20
xfer b22 f22
xfer b24 f24
xfer b26 f26
xfer b28 f28
xfer b30 f30
xfer b32 f32
xfer b34 f34
xfer b36 f36
xfer b38 f38
xfer b40 f40
xfer b42 f42
xfer b44 f44
xfer b46 f46
xfer b48 f48
xfer b50 f50
xfer b52 f52
xfer b54 f54
xfer b56 f56
xfer b58 f58
xfer b60 f60
xfer b1 f1
xfer b3 f3
xfer b5 f5
xfer b7 f7
xfer b9 f9
xfer b11 f11
xfer b13 f13
xfer b15 f15
xfer b17 f17
xfer b19 f19
xfer b21 f21
xfer b23 f23
xfer b25 f25
xfer b27 f27
xfer b29 f29
xfer b31 f31
xfer b33 f33
xfer b35 f35
xfer b37 f37
xfer b39 f39
xfer b41 f41
xfer b43 f43
xfer b45 f45
xfer b47 f47
xfer b49 f49
xfer b51 f51
xfer b53 f53
xfer b55 f55
xfer b57 f57
xfer b59 f59
xfer b61 f61
xfer b63 f63
xfer f1 b1
xfer f3 b3
xfer f5 b5
xfer f7 b7
xfer f9 b9
xfer f11 b11
xfer f13 b13
xfer f15 b15
xfer f17 b17
xfer f19 b19
xfer f21 b21
xfer f23 b23
xfer f25 b25
xfer f27 b27
xfer f29 b29
xfer f31 b31
xfer f33 b33
xfer f35 b35
xfer f37 b37
xfer f39 b39
xfer f41 b41
xfer f43 b43
xfer f45 b45
rack 2
xfer f47 b45
xfer f49 b47
xfer f51 b49
xfer f53 b51
xfer f55 b53
xfer f57 b55
xfer f59 b57
xfer f61 b59
xfer f63 b61
rack 0
xfer f0 b0
xfer f2 b2
xfer f4 b4
xfer f6 b6
xfer f8 b8
xfer f10 b10
xfer f12 b12
xfer f14 b14
xfer f16 b16
xfer f18 b18
xfer f20 b20
xfer f22 b22
xfer f24 b24
xfer f26 b26
xfer f28 b28
xfer f30 b30
xfer f32 b32
xfer f34 b34
xfer f36 b36
xfer f38 b38
xfer f40 b40
xfer f42 b42
xfer f44 b44
xfer f46 b46
xfer f48 b48
xfer f50 b50
xfer f52 b52
xfer f54 b54
xfer f56 b56
xfer f58 b58
xfer f60 b60
xfer b0 f0
xfer b2 f2
xfer b4 f4
xfer b6 f6
xfer b8 f8
xfer b10 f10
xfer b12 f12
xfer b14 f14
xfer b16 f16
xfer b18 f18
xfer b20 f20
xfer b22 f22
xfer b24 f24
xfer b26 f26
xfer b28 f28
xfer b30 f30
xfer b32 f32
xfer b34 f34
xfer b36 f36
xfer b38 f38
xfer b40 f40
xfer b42 f42
xfer b44 f44
xfer b46 f46
xfer b48 f48
xfer b50 f50
xfer b52 f52
xfer b54 f54
xfer b56 f56
xfer b58 f58
xfer b60 f60
xfer b1 f1
xfer b3 f3
xfer b5 f5
xfer b7 f7
xfer b9 f9
xfer b11 f11
xfer b13 f13
xfer b15 f15
xfer b17 f17
xfer b19 f19
xfer b21 f21
xfer b23 f23
xfer b25 f25
xfer b27 f27
xfer b29 f29
xfer b31 f31
xfer b33 f33
xfer b35 f35
xfer b37 f37
xfer b39 f39
xfer b41 f41
xfer b43 f43
xfer b45 f45
xfer b47 f47
xfer b49 f49
xfer b51 f51
xfer b53 f53
xfer b55 f55
xfer b57 f57
xfer b59 f59
xfer b61 f61
xfer f1 b1
xfer f3 b3
xfer f5 b5
xfer f7 b7
xfer f9 b9
xfer f11 b11
xfer f13 b13
xfer f15 b15
xfer f17 b17
xfer f19 b19
xfer f21 b21
xfer f23 b23
xfer f25 b25
xfer f27 b27
xfer f29 b29
xfer f31 b31
xfer f33 b33
xfer f35 b35
xfer f37 b37
xfer f39 b39
xfer f41 b41
xfer f43 b43
xfer f45 b45
xfer f47 b47
xfer f49 b49
xfer f51 b51
xfer f53 b53
xfer f55 b55
xfer f57 b57
xfer f59 b59
rack 2
xfer f61 b59
rack 0
knit + f36 1
knit + f38 1
knit + f40 1
knit + f42 1
knit + f44 1
knit + f46 1
knit + f48 1
knit + f50 1
knit + f52 1
knit + f54 1
knit + f56 1
knit + f58 1
knit + f60 1
knit - b59 1
knit - b57 1
knit - b55 1
knit - b53 1
knit - b51 1
knit - b49 1
knit - b47 1
knit - b45 1
knit - b43 1
knit - b41 1
knit - b39 1
knit - b37 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
xfer b59 f59
xfer b57 f57
xfer b55 f55
xfer b53 f53
xfer b51 f51
xfer b49 f49
xfer b47 f47
xfer b45 f45
xfer b43 f43
xfer b41 f41
xfer b39 f39
xfer b37 f37
xfer b35 f35
xfer b33 f33
xfer b31 f31
xfer b29 f29
xfer b27 f27
xfer b25 f25
xfer b23 f23
xfer b21 f21
xfer b19 f19
xfer b17 f17
xfer b15 f15
xfer b13 f13
xfer b11 f11
xfer b9 f9
xfer b7 f7
xfer b5 f5
xfer b3 f3
xfer b1 f1
xfer f1 b1
xfer f3 b3
xfer f5 b5
xfer f7 b7
xfer f9 b9
xfer f11 b11
xfer f13 b13
xfer f15 b15
xfer f17 b17
xfer f19 b19
xfer f21 b21
xfer f23 b23
xfer f25 b25
xfer f27 b27
xfer f29 b29
xfer f31 b31
xfer f33 b33
xfer f35 b35
xfer f37 b37
xfer f39 b39
xfer f41 b41
xfer f43 b43
xfer f45 b45
xfer f47 b47
xfer f49 b49
xfer f51 b51
xfer f53 b53
xfer f55 b55
xfer f57 b57
xfer f59 b59
xfer f0 b0
xfer f2 b2
xfer f4 b4
xfer f6 b6
xfer f8 b8
xfer f10 b10
xfer f12 b12
xfer f14 b14
xfer f16 b16
xfer f18 b18
xfer f20 b20
xfer f22 b22
xfer f24 b24
xfer f26 b26
xfer f28 b28
xfer f30 b30
xfer f32 b32
xfer f34 b34
xfer f36 b36
xfer f38 b38
xfer f40 b40
xfer f42 b42
xfer f44 b44
xfer f46 b46
xfer f48 b48
xfer f50 b50
xfer f52 b52
xfer f54 b54
xfer f56 b56
xfer f58 b58
xfer f60 b60
rack 2
xfer b0 f2
xfer b2 f4
xfer b4 f6
xfer b6 f8
rack -1
xfer b1 f0
rack 0
xfer b8 f8
xfer b10 f10
xfer b12 f12
xfer b14 f14
xfer b16 f16
xfer b18 f18
xfer b20 f20
xfer b22 f22
xfer b24 f24
xfer b26 f26
xfer b28 f28
rack -2
xfer b30 f28
xfer b32 f30
xfer b34 f32
xfer b36 f34
xfer b38 f36
xfer b40 f38
xfer b42 f40
xfer b44 f42
xfer b46 f44
xfer b48 f46
xfer b50 f48
xfer b52 f50
xfer b54 f52
xfer b56 f54
xfer b58 f56
xfer b60 f58
rack 0
xfer f0 b0
xfer f2 b2
xfer f4 b4
xfer f6 b6
xfer f8 b8
xfer f10 b10
xfer f12 b12
xfer f14 b14
xfer f16 b16
xfer f18 b18
xfer f20 b20
xfer f22 b22
xfer f24 b24
xfer f26 b26
xfer f28 b28
xfer f30 b30
rack 2
xfer f32 b30
xfer f34 b32
xfer f36 b34
xfer f38 b36
xfer f40 b38
xfer f42 b40
xfer f44 b42
xfer f46 b44
xfer f48 b46
xfer f50 b48
xfer f52 b50
xfer f54 b52
xfer f56 b54
xfer f58 b56
rack 0
xfer b0 f0
xfer b2 f2
xfer b4 f4
xfer b6 f6
xfer b8 f8
xfer b10 f10
xfer b12 f12
xfer b14 f14
xfer b16 f16
xfer b18 f18
xfer b20 f20
xfer b22 f22
xfer b24 f24
xfer b26 f26
xfer b28 f28
xfer b30 f30
xfer b32 f32
xfer b34 f34
xfer b36 f36
xfer b38 f38
xfer b40 f40
xfer b42 f42
xfer b44 f44
xfer b46 f46
xfer b48 f48
xfer b50 f50
xfer b52 f52
xfer b54 f54
xfer b56 f56
xfer b3 f3
xfer b5 f5
xfer b7 f7
xfer b9 f9
xfer b11 f11
xfer b13 f13
xfer b15 f15
xfer b17 f17
xfer b19 f19
xfer b21 f21
xfer b23 f23
xfer b25 f25
xfer b27 f27
xfer b29 f29
xfer b31 f31
xfer b33 f33
xfer b35 f35
xfer b37 f37
xfer b39 f39
xfer b41 f41
xfer b43 f43
xfer b45 f45
xfer b47 f47
xfer b49 f49
xfer b51 f51
xfer b53 f53
xfer b55 f55
xfer b57 f57
xfer b59 f59
rack 2
xfer f3 b1
xfer f5 b3
xfer f7 b5
xfer f9 b7
xfer f11 b9
xfer f13 b11
xfer f15 b13
xfer f17 b15
xfer f19 b17
xfer f21 b19
xfer f23 b21
xfer f25 b23
xfer f27 b25
xfer f29 b27
xfer f31 b29
xfer f33 b31
xfer f35 b33
xfer f37 b35
xfer f39 b37
xfer f41 b39
xfer f43 b41
xfer f45 b43
xfer f47 b45
xfer f49 b47
xfer f51 b49
xfer f53 b51
xfer f55 b53
xfer f57 b55
xfer f59 b57
rack 0
knit - b17 1
knit - b15 1
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit + f36 1
knit + f38 1
knit + f40 1
knit + f42 1
knit + f44 1
knit + f46 1
knit + f48 1
knit + f50 1
knit + f52 1
knit + f54 1
knit + f56 1
knit - b57 1
knit - b55 1
knit - b53 1
knit - b51 1
knit - b49 1
knit - b47 1
knit - b45 1
knit - b43 1
knit - b41 1
knit - b39 1
knit - b37 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
knit - b17 1
knit - b15 1
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit + f36 1
knit + f38 1
knit + f40 1
knit + f42 1
knit + f44 1
knit + f46 1
knit + f48 1
knit + f50 1
knit + f52 1
knit + f54 1
knit + f56 1
knit - b57 1
knit - b55 1
knit - b53 1
knit - b51 1
knit - b49 1
knit - b47 1
knit - b45 1
knit - b43 1
knit - b41 1
knit - b39 1
knit - b37 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
knit - b17 1
knit - b15 1
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit + f36 1
knit + f38 1
knit + f40 1
knit + f42 1
knit + f44 1
knit + f46 1
knit + f48 1
knit + f50 1
knit + f52 1
knit + f54 1
knit + f56 1
knit - b57 1
knit - b55 1
knit - b53 1
knit - b51 1
knit - b49 1
knit - b47 1
knit - b45 1
knit - b43 1
knit - b41 1
knit - b39 1
knit - b37 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
knit - b17 1
knit - b15 1
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit + f36 1
knit + f38 1
knit + f40 1
knit + f42 1
knit + f44 1
knit + f46 1
knit + f48 1
knit + f50 1
knit + f52 1
knit + f54 1
knit + f56 1
knit - b57 1
knit - b55 1
knit - b53 1
knit - b51 1
knit - b49 1
knit - b47 1
knit - b45 1
knit - b43 1
knit - b41 1
knit - b39 1
knit - b37 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
knit - b17 1
knit - b15 1
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit + f36 1
knit + f38 1
knit + f40 1
knit + f42 1
knit + f44 1
knit + f46 1
knit + f48 1
knit + f50 1
knit + f52 1
knit + f54 1
knit + f56 1
knit - b57 1
knit - b55 1
knit - b53 1
knit - b51 1
knit - b49 1
knit - b47 1
knit - b45 1
knit - b43 1
knit - b41 1
knit - b39 1
knit - b37 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
xfer f0 b0
xfer f2 b2
xfer f4 b4
xfer f6 b6
xfer f8 b8
xfer f10 b10
xfer f12 b12
xfer f14 b14
xfer f16 b16
xfer f18 b18
xfer f20 b20
xfer f22 b22
xfer f24 b24
xfer f26 b26
xfer f28 b28
xfer f30 b30
xfer f32 b32
xfer f34 b34
xfer f36 b36
xfer f38 b38
xfer f40 b40
xfer f42 b42
xfer f44 b44
xfer f46 b46
xfer f48 b48
xfer f50 b50
xfer f52 b52
xfer f54 b54
rack 2
xfer f56 b54
rack 0
xfer b0 f0
xfer b2 f2
xfer b4 f4
xfer b6 f6
xfer b8 f8
xfer b10 f10
xfer b12 f12
xfer b14 f14
xfer b16 f16
xfer b18 f18
xfer b20 f20
xfer b22 f22
xfer b24 f24
xfer b26 f26
xfer b28 f28
xfer b30 f30
xfer b32 f32
xfer b34 f34
xfer b36 f36
xfer b38 f38
xfer b40 f40
xfer b42 f42
xfer b44 f44
xfer b46 f46
xfer b48 f48
xfer b50 f50
xfer b52 f52
xfer b54 f54
xfer b1 f1
xfer b3 f3
xfer b5 f5
xfer b7 f7
xfer b9 f9
xfer b11 f11
xfer b13 f13
xfer b15 f15
xfer b17 f17
xfer b19 f19
xfer b21 f21
xfer b23 f23
xfer b25 f25
xfer b27 f27
xfer b29 f29
xfer b31 f31
xfer b33 f33
xfer b35 f35
xfer b37 f37
xfer b39 f39
xfer b41 f41
xfer b43 f43
xfer b45 f45
xfer b47 f47
xfer b49 f49
xfer b51 f51
xfer b53 f53
xfer b55 f55
xfer b57 f57
xfer f1 b1
xfer f3 b3
xfer f5 b5
xfer f7 b7
xfer f9 b9
xfer f11 b11
xfer f13 b13
xfer f15 b15
xfer f17 b17
xfer f19 b19
xfer f21 b21
xfer f23 b23
xfer f25 b25
xfer f27 b27
xfer f29 b29
xfer f31 b31
xfer f33 b33
xfer f35 b35
xfer f37 b37
xfer f39 b39
xfer f41 b41
xfer f43 b43
xfer f45 b45
xfer f47 b47
xfer f49 b49
xfer f51 b51
xfer f53 b53
xfer f55 b55
rack 2
xfer f57 b55
rack 0
knit - b17 1
knit - b15 1
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit + f36 1
knit + f38 1
knit + f40 1
knit + f42 1
knit + f44 1
knit + f46 1
knit + f48 1
knit + f50 1
knit + f52 1
knit + f54 1
knit - b55 1
knit - b53 1
knit - b51 1
knit - b49 1
knit - b47 1
knit - b45 1
knit - b43 1
knit - b41 1
knit - b39 1
knit - b37 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
xfer b1 f1
xfer b3 f3
xfer b5 f5
xfer b7 f7
xfer b9 f9
xfer b11 f11
xfer b13 f13
xfer b15 f15
xfer b17 f17
xfer b19 f19
xfer b21 f21
xfer b23 f23
xfer b25 f25
xfer b27 f27
xfer b29 f29
xfer b31 f31
xfer b33 f33
xfer b35 f35
xfer b37 f37
xfer b39 f39
xfer b41 f41
xfer b43 f43
xfer b45 f45
xfer b47 f47
xfer b49 f49
xfer b51 f51
xfer b53 f53
xfer b55 f55
xfer f1 b1
xfer f3 b3
xfer f5 b5
xfer f7 b7
xfer f9 b9
xfer f11 b11
xfer f13 b13
xfer f15 b15
xfer f17 b17
xfer f19 b19
xfer f21 b21
xfer f23 b23
xfer f25 b25
xfer f27 b27
xfer f29 b29
xfer f31 b31
xfer f33 b33
xfer f35 b35
xfer f37 b37
xfer f39 b39
xfer f41 b41
xfer f43 b43
xfer f45 b45
xfer f47 b47
xfer f49 b49
xfer f51 b51
xfer f53 b53
xfer f55 b55
xfer f0 b0
xfer f2 b2
xfer f4 b4
xfer f6 b6
xfer f8 b8
xfer f10 b10
xfer f12 b12
xfer f14 b14
xfer f16 b16
xfer f18 b18
xfer f20 b20
xfer f22 b22
xfer f24 b24
xfer f26 b26
xfer f28 b28
xfer f30 b30
xfer f32 b32
xfer f34 b34
xfer f36 b36
xfer f38 b38
xfer f40 b40
xfer f42 b42
xfer f44 b44
xfer f46 b46
xfer f48 b48
xfer f50 b50
xfer f52 b52
xfer f54 b54
xfer b0 f0
xfer b2 f2
xfer b4 f4
xfer b6 f6
xfer b8 f8
xfer b10 f10
xfer b12 f12
xfer b14 f14
xfer b16 f16
xfer b18 f18
xfer b20 f20
xfer b22 f22
xfer b24 f24
xfer b26 f26
rack -2
xfer b28 f26
xfer b30 f28
xfer b32 f30
xfer b34 f32
xfer b36 f34
xfer b38 f36
xfer b40 f38
xfer b42 f40
xfer b44 f42
xfer b46 f44
xfer b48 f46
xfer b50 f48
xfer b52 f50
xfer b54 f52
rack -1
xfer b55 f54
rack 0
xfer f0 b0
xfer f2 b2
xfer f4 b4
xfer f6 b6
xfer f8 b8
xfer f10 b10
xfer f12 b12
xfer f14 b14
xfer f16 b16
xfer f18 b18
xfer f20 b20
xfer f22 b22
xfer f24 b24
xfer f26 b26
xfer f28 b28
rack 2
xfer f30 b28
xfer f32 b30
xfer f34 b32
xfer f36 b34
xfer f38 b36
xfer f40 b38
xfer f42 b40
xfer f44 b42
xfer f46 b44
xfer f48 b46
xfer f50 b48
xfer f52 b50
xfer f54 b52
rack 0
xfer b0 f0
xfer b2 f2
xfer b4 f4
xfer b6 f6
xfer b8 f8
xfer b10 f10
xfer b12 f12
xfer b14 f14
xfer b16 f16
xfer b18 f18
xfer b20 f20
xfer b22 f22
xfer b24 f24
xfer b26 f26
xfer b28 f28
xfer b30 f30
xfer b32 f32
xfer b34 f34
xfer b36 f36
xfer b38 f38
xfer b40 f40
xfer b42 f42
xfer b44 f44
xfer b46 f46
xfer b48 f48
xfer b50 f50
xfer b52 f52
xfer b1 f1
xfer b3 f3
xfer b5 f5
xfer b7 f7
xfer b9 f9
xfer b11 f11
xfer b13 f13
xfer b15 f15
xfer b17 f17
xfer b19 f19
xfer b21 f21
xfer b23 f23
xfer b25 f25
xfer b27 f27
xfer b29 f29
xfer b31 f31
xfer b33 f33
xfer b35 f35
xfer b37 f37
xfer b39 f39
xfer b41 f41
xfer b43 f43
xfer b45 f45
xfer b47 f47
xfer b49 f49
xfer b51 f51
xfer b53 f53
xfer f1 b1
xfer f3 b3
xfer f5 b5
xfer f7 b7
xfer f9 b9
xfer f11 b11
xfer f13 b13
xfer f15 b15
xfer f17 b17
xfer f19 b19
xfer f21 b21
xfer f23 b23
xfer f25 b25
xfer f27 b27
xfer f29 b29
xfer f31 b31
xfer f33 b33
xfer f35 b35
xfer f37 b37
xfer f39 b39
xfer f41 b41
xfer f43 b43
xfer f45 b45
xfer f47 b47
xfer f49 b49
xfer f51 b51
xfer f53 b53
rack 0
knit - b17 1
knit - b15 1
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit + f36 1
knit + f38 1
knit + f40 1
knit + f42 1
knit + f44 1
knit + f46 1
knit + f48 1
knit + f50 1
knit + f52 1
knit - b53 1
knit - b51 1
knit - b49 1
knit - b47 1
knit - b45 1
knit - b43 1
knit - b41 1
knit - b39 1
knit - b37 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
knit - b17 1
knit - b15 1
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit + f36 1
knit + f38 1
knit + f40 1
knit + f42 1
knit + f44 1
knit + f46 1
knit + f48 1
knit + f50 1
knit + f52 1
knit - b53 1
knit - b51 1
knit - b49 1
knit - b47 1
knit - b45 1
knit - b43 1
knit - b41 1
knit - b39 1
knit - b37 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
knit - b17 1
knit - b15 1
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit + f36 1
knit + f38 1
knit + f40 1
knit + f42 1
knit + f44 1
knit + f46 1
knit + f48 1
knit + f50 1
knit + f52 1
knit - b53 1
knit - b51 1
knit - b49 1
knit - b47 1
knit - b45 1
knit - b43 1
knit - b41 1
knit - b39 1
knit - b37 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
xfer f0 b0
xfer f2 b2
xfer f4 b4
xfer f6 b6
xfer f8 b8
xfer f10 b10
xfer f12 b12
xfer f14 b14
xfer f16 b16
xfer f18 b18
xfer f20 b20
xfer f22 b22
xfer f24 b24
xfer f26 b26
xfer f28 b28
xfer f30 b30
xfer f32 b32
xfer f34 b34
xfer f36 b36
xfer f38 b38
xfer f40 b40
xfer f42 b42
xfer f44 b44
xfer f46 b46
xfer f48 b48
xfer f50 b50
rack -1
xfer f52 b53
rack 0
xfer b0 f0
xfer b2 f2
xfer b4 f4
xfer b6 f6
xfer b8 f8
xfer b10 f10
xfer b12 f12
xfer b14 f14
xfer b16 f16
xfer b18 f18
xfer b20 f20
xfer b22 f22
xfer b24 f24
xfer b26 f26
xfer b28 f28
xfer b30 f30
xfer b32 f32
xfer b34 f34
xfer b36 f36
xfer b38 f38
xfer b40 f40
xfer b42 f42
xfer b44 f44
xfer b46 f46
xfer b48 f48
xfer b50 f50
xfer b1 f1
xfer b3 f3
xfer b5 f5
xfer b7 f7
xfer b9 f9
xfer b11 f11
xfer b13 f13
xfer b15 f15
xfer b17 f17
xfer b19 f19
xfer b21 f21
xfer b23 f23
xfer b25 f25
xfer b27 f27
xfer b29 f29
xfer b31 f31
xfer b33 f33
xfer b35 f35
xfer b37 f37
xfer b39 f39
xfer b41 f41
xfer b43 f43
xfer b45 f45
xfer b47 f47
xfer b49 f49
xfer b51 f51
xfer b53 f53
xfer f1 b1
xfer f3 b3
xfer f5 b5
xfer f7 b7
xfer f9 b9
xfer f11 b11
xfer f13 b13
xfer f15 b15
xfer f17 b17
xfer f19 b19
xfer f21 b21
xfer f23 b23
xfer f25 b25
xfer f27 b27
xfer f29 b29
xfer f31 b31
xfer f33 b33
xfer f35 b35
xfer f37 b37
rack 2
xfer f39 b37
xfer f41 b39
xfer f43 b41
xfer f45 b43
xfer f47 b45
xfer f49 b47
xfer f51 b49
xfer f53 b51
rack 0
knit - b17 1
knit - b15 1
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit + f36 1
knit + f38 1
knit + f40 1
knit + f42 1
knit + f44 1
knit + f46 1
knit + f48 1
knit + f50 1
knit - b51 1
knit - b49 1
knit - b47 1
knit - b45 1
knit - b43 1
knit - b41 1
knit - b39 1
knit - b37 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
rack -2
xfer b51 f49
xfer b49 f47
xfer b47 f45
xfer b45 f43
xfer b43 f41
xfer b41 f39
xfer b39 f37
xfer b37 f35
xfer b35 f33
xfer b33 f31
xfer b31 f29
xfer b29 f27
xfer b27 f25
xfer b25 f23
xfer b23 f21
xfer b21 f19
xfer b19 f17
xfer b17 f15
xfer b15 f13
xfer b13 f11
xfer b11 f9
xfer b9 f7
xfer b7 f5
xfer b5 f3
xfer b3 f1
rack -3
xfer b1 f-2
rack 0
xfer f1 b1
xfer f3 b3
xfer f5 b5
xfer f7 b7
xfer f9 b9
xfer f11 b11
xfer f13 b13
xfer f15 b15
xfer f17 b17
xfer f19 b19
xfer f21 b21
xfer f23 b23
xfer f25 b25
xfer f27 b27
xfer f29 b29
xfer f31 b31
xfer f33 b33
xfer f35 b35
xfer f37 b37
xfer f39 b39
xfer f41 b41
xfer f43 b43
xfer f45 b45
xfer f47 b47
xfer f49 b49
xfer f-2 b-2
xfer f0 b0
xfer f2 b2
xfer f4 b4
xfer f6 b6
xfer f8 b8
xfer f10 b10
xfer f12 b12
xfer f14 b14
xfer f16 b16
xfer f18 b18
xfer f20 b20
xfer f22 b22
xfer f24 b24
xfer f26 b26
xfer f28 b28
xfer f30 b30
xfer f32 b32
xfer f34 b34
xfer f36 b36
xfer f38 b38
xfer f40 b40
xfer f42 b42
xfer f44 b44
xfer f46 b46
xfer f48 b48
xfer f50 b50
rack 2
xfer b-2 f0
xfer b0 f2
xfer b2 f4
xfer b4 f6
xfer b6 f8
xfer b8 f10
rack 0
xfer b10 f10
xfer b12 f12
xfer b14 f14
xfer b16 f16
xfer b18 f18
xfer b20 f20
xfer b22 f22
xfer b24 f24
rack -2
xfer b26 f24
xfer b28 f26
xfer b30 f28
xfer b32 f30
xfer b34 f32
xfer b36 f34
xfer b38 f36
xfer b40 f38
xfer b42 f40
xfer b44 f42
xfer b46 f44
xfer b48 f46
xfer b50 f48
rack 0
knit - b15 1
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit + f36 1
knit + f38 1
knit + f40 1
knit + f42 1
knit + f44 1
knit + f46 1
knit + f48 1
knit - b49 1
knit - b47 1
knit - b45 1
knit - b43 1
knit - b41 1
knit - b39 1
knit - b37 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
knit - b17 1
knit - b15 1
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit + f36 1
knit + f38 1
knit + f40 1
knit + f42 1
knit + f44 1
knit + f46 1
knit + f48 1
knit - b49 1
knit - b47 1
knit - b45 1
knit - b43 1
knit - b41 1
knit - b39 1
knit - b37 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
knit - b17 1
knit - b15 1
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit + f36 1
knit + f38 1
knit + f40 1
knit + f42 1
knit + f44 1
knit + f46 1
knit + f48 1
knit - b49 1
knit - b47 1
knit - b45 1
knit - b43 1
knit - b41 1
knit - b39 1
knit - b37 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
knit - b17 1
xfer f0 b0
xfer f2 b2
xfer f4 b4
xfer f6 b6
xfer f8 b8
xfer f10 b10
xfer f12 b12
xfer f14 b14
xfer f16 b16
xfer f18 b18
xfer f20 b20
xfer f22 b22
xfer f24 b24
xfer f26 b26
xfer f28 b28
xfer f30 b30
xfer f32 b32
xfer f34 b34
xfer f36 b36
xfer f38 b38
xfer f40 b40
xfer f42 b42
xfer f44 b44
xfer f46 b46
rack 2
xfer f48 b46
rack 0
xfer b0 f0
xfer b2 f2
xfer b4 f4
xfer b6 f6
xfer b8 f8
xfer b10 f10
xfer b12 f12
xfer b14 f14
xfer b16 f16
xfer b18 f18
xfer b20 f20
xfer b22 f22
xfer b24 f24
xfer b26 f26
xfer b28 f28
xfer b30 f30
xfer b32 f32
xfer b34 f34
xfer b36 f36
xfer b38 f38
xfer b40 f40
xfer b42 f42
xfer b44 f44
xfer b46 f46
xfer b1 f1
xfer b3 f3
xfer b5 f5
xfer b7 f7
xfer b9 f9
xfer b11 f11
xfer b13 f13
xfer b15 f15
xfer b17 f17
xfer b19 f19
xfer b21 f21
xfer b23 f23
xfer b25 f25
xfer b27 f27
xfer b29 f29
xfer b31 f31
xfer b33 f33
xfer b35 f35
xfer b37 f37
xfer b39 f39
xfer b41 f41
xfer b43 f43
xfer b45 f45
xfer b47 f47
xfer b49 f49
xfer f1 b1
xfer f3 b3
xfer f5 b5
xfer f7 b7
xfer f9 b9
xfer f11 b11
xfer f13 b13
xfer f15 b15
xfer f17 b17
xfer f19 b19
xfer f21 b21
xfer f23 b23
xfer f25 b25
xfer f27 b27
xfer f29 b29
xfer f31 b31
xfer f33 b33
xfer f35 b35
xfer f37 b37
xfer f39 b39
xfer f41 b41
xfer f43 b43
xfer f45 b45
xfer f47 b47
rack 2
xfer f49 b47
rack 0
knit - b15 1
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit + f36 1
knit + f38 1
knit + f40 1
knit + f42 1
knit + f44 1
knit + f46 1
knit - b47 1
knit - b45 1
knit - b43 1
knit - b41 1
knit - b39 1
knit - b37 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
knit - b17 1
rack -2
xfer b47 f45
xfer b45 f43
xfer b43 f41
xfer b41 f39
xfer b39 f37
xfer b37 f35
xfer b35 f33
xfer b33 f31
xfer b31 f29
xfer b29 f27
xfer b27 f25
xfer b25 f23
xfer b23 f21
xfer b21 f19
xfer b19 f17
xfer b17 f15
xfer b15 f13
xfer b13 f11
xfer b11 f9
xfer b9 f7
xfer b7 f5
xfer b5 f3
xfer b3 f1
rack -3
xfer b1 f-2
rack 0
xfer f1 b1
xfer f3 b3
xfer f5 b5
xfer f7 b7
xfer f9 b9
xfer f11 b11
xfer f13 b13
xfer f15 b15
xfer f17 b17
xfer f19 b19
xfer f21 b21
xfer f23 b23
xfer f25 b25
xfer f27 b27
xfer f29 b29
xfer f31 b31
xfer f33 b33
xfer f35 b35
xfer f37 b37
xfer f39 b39
xfer f41 b41
xfer f43 b43
xfer f45 b45
xfer f-2 b-2
xfer f0 b0
xfer f2 b2
xfer f4 b4
xfer f6 b6
xfer f8 b8
xfer f10 b10
xfer f12 b12
xfer f14 b14
xfer f16 b16
xfer f18 b18
xfer f20 b20
xfer f22 b22
xfer f24 b24
xfer f26 b26
xfer f28 b28
xfer f30 b30
xfer f32 b32
xfer f34 b34
xfer f36 b36
xfer f38 b38
xfer f40 b40
xfer f42 b42
xfer f44 b44
xfer f46 b46
rack 2
xfer b-2 f0
xfer b0 f2
xfer b2 f4
xfer b4 f6
xfer b6 f8
xfer b8 f10
xfer b10 f12
xfer b12 f14
xfer b14 f16
xfer b16 f18
xfer b18 f20
xfer b20 f22
xfer b22 f24
rack 0
xfer b24 f24
xfer b26 f26
rack -2
xfer b28 f26
xfer b30 f28
xfer b32 f30
xfer b34 f32
xfer b36 f34
xfer b38 f36
xfer b40 f38
xfer b42 f40
xfer b44 f42
xfer b46 f44
rack 0
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit + f36 1
knit + f38 1
knit + f40 1
knit + f42 1
knit + f44 1
knit - b45 1
knit - b43 1
knit - b41 1
knit - b39 1
knit - b37 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
knit - b17 1
knit - b15 1
xfer f0 b0
xfer f2 b2
xfer f4 b4
xfer f6 b6
xfer f8 b8
xfer f10 b10
xfer f12 b12
xfer f14 b14
xfer f16 b16
xfer f18 b18
xfer f20 b20
xfer f22 b22
xfer f24 b24
xfer f26 b26
xfer f28 b28
xfer f30 b30
xfer f32 b32
xfer f34 b34
xfer f36 b36
xfer f38 b38
xfer f40 b40
xfer f42 b42
rack 2
xfer f44 b42
rack 0
xfer b0 f0
xfer b2 f2
xfer b4 f4
xfer b6 f6
xfer b8 f8
xfer b10 f10
xfer b12 f12
xfer b14 f14
xfer b16 f16
xfer b18 f18
xfer b20 f20
xfer b22 f22
xfer b24 f24
xfer b26 f26
xfer b28 f28
xfer b30 f30
xfer b32 f32
xfer b34 f34
xfer b36 f36
xfer b38 f38
xfer b40 f40
xfer b42 f42
xfer b1 f1
xfer b3 f3
xfer b5 f5
xfer b7 f7
xfer b9 f9
xfer b11 f11
xfer b13 f13
xfer b15 f15
xfer b17 f17
xfer b19 f19
xfer b21 f21
xfer b23 f23
xfer b25 f25
xfer b27 f27
xfer b29 f29
xfer b31 f31
xfer b33 f33
xfer b35 f35
xfer b37 f37
xfer b39 f39
xfer b41 f41
xfer b43 f43
xfer b45 f45
xfer f1 b1
xfer f3 b3
xfer f5 b5
xfer f7 b7
xfer f9 b9
xfer f11 b11
xfer f13 b13
xfer f15 b15
xfer f17 b17
xfer f19 b19
xfer f21 b21
xfer f23 b23
xfer f25 b25
xfer f27 b27
xfer f29 b29
xfer f31 b31
xfer f33 b33
xfer f35 b35
xfer f37 b37
xfer f39 b39
xfer f41 b41
xfer f43 b43
rack 2
xfer f45 b43
rack 0
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit + f36 1
knit + f38 1
knit + f40 1
knit + f42 1
knit - b43 1
knit - b41 1
knit - b39 1
knit - b37 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
knit - b17 1
knit - b15 1
xfer b1 f1
xfer b3 f3
xfer b5 f5
xfer b7 f7
xfer b9 f9
xfer b11 f11
xfer b13 f13
xfer b15 f15
xfer b17 f17
xfer b19 f19
xfer b21 f21
xfer b23 f23
xfer b25 f25
xfer b27 f27
xfer b29 f29
xfer b31 f31
xfer b33 f33
xfer b35 f35
xfer b37 f37
xfer b39 f39
xfer b41 f41
xfer b43 f43
xfer f1 b1
xfer f3 b3
xfer f5 b5
xfer f7 b7
xfer f9 b9
xfer f11 b11
xfer f13 b13
xfer f15 b15
xfer f17 b17
xfer f19 b19
xfer f21 b21
xfer f23 b23
xfer f25 b25
xfer f27 b27
xfer f29 b29
xfer f31 b31
xfer f33 b33
xfer f35 b35
xfer f37 b37
xfer f39 b39
xfer f41 b41
xfer f43 b43
xfer f0 b0
xfer f2 b2
xfer f4 b4
xfer f6 b6
xfer f8 b8
xfer f10 b10
xfer f12 b12
xfer f14 b14
xfer f16 b16
xfer f18 b18
xfer f20 b20
xfer f22 b22
xfer f24 b24
xfer f26 b26
xfer f28 b28
xfer f30 b30
xfer f32 b32
xfer f34 b34
xfer f36 b36
xfer f38 b38
xfer f40 b40
xfer f42 b42
xfer b0 f0
xfer b2 f2
xfer b4 f4
xfer b6 f6
xfer b8 f8
xfer b10 f10
xfer b12 f12
xfer b14 f14
xfer b16 f16
xfer b18 f18
xfer b20 f20
xfer b22 f22
rack -2
xfer b24 f22
xfer b26 f24
xfer b28 f26
xfer b30 f28
xfer b32 f30
xfer b34 f32
xfer b36 f34
xfer b38 f36
xfer b40 f38
xfer b42 f40
rack -1
xfer b43 f42
rack 0
xfer f0 b0
xfer f2 b2
xfer f4 b4
xfer f6 b6
xfer f8 b8
xfer f10 b10
xfer f12 b12
xfer f14 b14
xfer f16 b16
xfer f18 b18
xfer f20 b20
xfer f22 b22
xfer f24 b24
rack 2
xfer f26 b24
xfer f28 b26
xfer f30 b28
xfer f32 b30
xfer f34 b32
xfer f36 b34
xfer f38 b36
xfer f40 b38
xfer f42 b40
rack 0
xfer b0 f0
xfer b2 f2
xfer b4 f4
xfer b6 f6
xfer b8 f8
xfer b10 f10
xfer b12 f12
xfer b14 f14
xfer b16 f16
xfer b18 f18
xfer b20 f20
xfer b22 f22
xfer b24 f24
xfer b26 f26
xfer b28 f28
xfer b30 f30
xfer b32 f32
xfer b34 f34
xfer b36 f36
xfer b38 f38
xfer b40 f40
xfer b1 f1
xfer b3 f3
xfer b5 f5
xfer b7 f7
xfer b9 f9
xfer b11 f11
xfer b13 f13
xfer b15 f15
xfer b17 f17
xfer b19 f19
xfer b21 f21
xfer b23 f23
xfer b25 f25
xfer b27 f27
xfer b29 f29
xfer b31 f31
xfer b33 f33
xfer b35 f35
xfer b37 f37
xfer b39 f39
xfer b41 f41
xfer f1 b1
xfer f3 b3
xfer f5 b5
xfer f7 b7
xfer f9 b9
xfer f11 b11
xfer f13 b13
xfer f15 b15
xfer f17 b17
xfer f19 b19
xfer f21 b21
xfer f23 b23
xfer f25 b25
xfer f27 b27
xfer f29 b29
xfer f31 b31
xfer f33 b33
xfer f35 b35
xfer f37 b37
xfer f39 b39
xfer f41 b41
rack 0
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit + f36 1
knit + f38 1
knit + f40 1
knit - b41 1
knit - b39 1
knit - b37 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
knit - b17 1
knit - b15 1
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit + f36 1
knit + f38 1
knit + f40 1
knit - b41 1
knit - b39 1
knit - b37 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
knit - b17 1
knit - b15 1
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit + f36 1
knit + f38 1
knit + f40 1
knit - b41 1
knit - b39 1
knit - b37 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
knit - b17 1
knit - b15 1
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit + f36 1
knit + f38 1
knit + f40 1
knit - b41 1
knit - b39 1
knit - b37 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
knit - b17 1
knit - b15 1
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit + f36 1
knit + f38 1
knit + f40 1
knit - b41 1
knit - b39 1
knit - b37 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
knit - b17 1
knit - b15 1
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit + f36 1
knit + f38 1
knit + f40 1
knit - b41 1
knit - b39 1
knit - b37 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
knit - b17 1
knit - b15 1
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit + f36 1
knit + f38 1
knit + f40 1
knit - b41 1
knit - b39 1
knit - b37 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
knit - b17 1
knit - b15 1
xfer f0 b0
xfer f2 b2
xfer f4 b4
xfer f6 b6
xfer f8 b8
xfer f10 b10
xfer f12 b12
xfer f14 b14
xfer f16 b16
xfer f18 b18
xfer f20 b20
xfer f22 b22
xfer f24 b24
xfer f26 b26
xfer f28 b28
xfer f30 b30
xfer f32 b32
xfer f34 b34
xfer f36 b36
xfer f38 b38
xfer f40 b40
xfer b0 f0
xfer b2 f2
xfer b4 f4
xfer b6 f6
xfer b8 f8
xfer b10 f10
xfer b12 f12
xfer b14 f14
xfer b16 f16
xfer b18 f18
xfer b20 f20
xfer b22 f22
xfer b24 f24
xfer b26 f26
xfer b28 f28
xfer b30 f30
xfer b32 f32
xfer b34 f34
xfer b36 f36
xfer b38 f38
xfer b40 f40
xfer b1 f1
xfer b3 f3
xfer b5 f5
xfer b7 f7
xfer b9 f9
xfer b11 f11
xfer b13 f13
xfer b15 f15
xfer b17 f17
xfer b19 f19
xfer b21 f21
xfer b23 f23
xfer b25 f25
xfer b27 f27
xfer b29 f29
xfer b31 f31
xfer b33 f33
xfer b35 f35
xfer b37 f37
xfer b39 f39
xfer b41 f41
xfer f1 b1
xfer f3 b3
xfer f5 b5
xfer f7 b7
xfer f9 b9
xfer f11 b11
xfer f13 b13
xfer f15 b15
xfer f17 b17
xfer f19 b19
xfer f21 b21
xfer f23 b23
xfer f25 b25
xfer f27 b27
xfer f29 b29
xfer f31 b31
rack 2
xfer f33 b31
xfer f35 b33
xfer f37 b35
xfer f39 b37
xfer f41 b39
rack 0
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit + f36 1
knit + f38 1
knit + f40 1
knit - b39 1
knit - b37 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
knit - b17 1
knit - b15 1
xfer f0 b0
xfer f2 b2
xfer f4 b4
xfer f6 b6
xfer f8 b8
xfer f10 b10
xfer f12 b12
rack 2
xfer f14 b12
xfer f16 b14
xfer f18 b16
xfer f20 b18
xfer f22 b20
xfer f24 b22
xfer f26 b24
xfer f28 b26
xfer f30 b28
xfer f32 b30
xfer f34 b32
xfer f36 b34
xfer f38 b36
xfer f40 b38
rack 0
xfer b0 f0
xfer b2 f2
xfer b4 f4
xfer b6 f6
xfer b8 f8
xfer b10 f10
xfer b12 f12
xfer b14 f14
xfer b16 f16
xfer b18 f18
xfer b20 f20
xfer b22 f22
xfer b24 f24
xfer b26 f26
xfer b28 f28
xfer b30 f30
xfer b32 f32
xfer b34 f34
xfer b36 f36
xfer b38 f38
xfer b1 f1
xfer b3 f3
xfer b5 f5
xfer b7 f7
xfer b9 f9
xfer b11 f11
xfer b13 f13
xfer b15 f15
xfer b17 f17
xfer b19 f19
xfer b21 f21
xfer b23 f23
xfer b25 f25
xfer b27 f27
xfer b29 f29
xfer b31 f31
xfer b33 f33
xfer b35 f35
xfer b37 f37
xfer b39 f39
xfer f1 b1
xfer f3 b3
xfer f5 b5
xfer f7 b7
xfer f9 b9
xfer f11 b11
xfer f13 b13
xfer f15 b15
xfer f17 b17
xfer f19 b19
xfer f21 b21
xfer f23 b23
xfer f25 b25
xfer f27 b27
xfer f29 b29
xfer f31 b31
xfer f33 b33
xfer f35 b35
xfer f37 b37
xfer f39 b39
rack 0
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit + f36 1
knit + f38 1
knit - b39 1
knit - b37 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
knit - b17 1
knit - b15 1
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit + f36 1
knit + f38 1
knit - b39 1
knit - b37 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
knit - b17 1
knit - b15 1
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit + f36 1
knit + f38 1
knit - b39 1
knit - b37 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
knit - b17 1
knit - b15 1
xfer f0 b0
xfer f2 b2
xfer f4 b4
xfer f6 b6
xfer f8 b8
xfer f10 b10
xfer f12 b12
xfer f14 b14
xfer f16 b16
xfer f18 b18
xfer f20 b20
xfer f22 b22
xfer f24 b24
xfer f26 b26
xfer f28 b28
xfer f30 b30
xfer f32 b32
xfer f34 b34
xfer f36 b36
xfer f38 b38
xfer b0 f0
xfer b2 f2
xfer b4 f4
xfer b6 f6
xfer b8 f8
xfer b10 f10
xfer b12 f12
xfer b14 f14
xfer b16 f16
xfer b18 f18
xfer b20 f20
xfer b22 f22
xfer b24 f24
xfer b26 f26
xfer b28 f28
xfer b30 f30
xfer b32 f32
xfer b34 f34
xfer b36 f36
xfer b38 f38
xfer b1 f1
xfer b3 f3
xfer b5 f5
xfer b7 f7
xfer b9 f9
xfer b11 f11
xfer b13 f13
xfer b15 f15
xfer b17 f17
xfer b19 f19
xfer b21 f21
xfer b23 f23
xfer b25 f25
xfer b27 f27
xfer b29 f29
xfer b31 f31
xfer b33 f33
xfer b35 f35
xfer b37 f37
xfer b39 f39
xfer f1 b1
xfer f3 b3
xfer f5 b5
xfer f7 b7
xfer f9 b9
xfer f11 b11
xfer f13 b13
xfer f15 b15
xfer f17 b17
xfer f19 b19
xfer f21 b21
xfer f23 b23
xfer f25 b25
xfer f27 b27
xfer f29 b29
rack 2
xfer f31 b29
xfer f33 b31
xfer f35 b33
xfer f37 b35
xfer f39 b37
rack -1
xfer f38 b39
rack 0
xfer f0 b0
xfer f2 b2
xfer f4 b4
xfer f6 b6
xfer f8 b8
xfer f10 b10
xfer f12 b12
xfer f14 b14
xfer f16 b16
xfer f18 b18
xfer f20 b20
xfer f22 b22
xfer f24 b24
xfer f26 b26
xfer f28 b28
xfer f30 b30
xfer f32 b32
xfer f34 b34
xfer f36 b36
xfer b0 f0
xfer b2 f2
xfer b4 f4
xfer b6 f6
xfer b8 f8
xfer b10 f10
xfer b12 f12
xfer b14 f14
xfer b16 f16
xfer b18 f18
xfer b20 f20
xfer b22 f22
xfer b24 f24
xfer b26 f26
xfer b28 f28
xfer b30 f30
xfer b32 f32
xfer b34 f34
xfer b36 f36
xfer b1 f1
xfer b3 f3
xfer b5 f5
xfer b7 f7
xfer b9 f9
xfer b11 f11
xfer b13 f13
xfer b15 f15
xfer b17 f17
xfer b19 f19
xfer b21 f21
xfer b23 f23
xfer b25 f25
xfer b27 f27
xfer b29 f29
xfer b31 f31
xfer b33 f33
xfer b35 f35
xfer b37 f37
xfer b39 f39
xfer f1 b1
xfer f3 b3
xfer f5 b5
xfer f7 b7
xfer f9 b9
xfer f11 b11
xfer f13 b13
xfer f15 b15
xfer f17 b17
xfer f19 b19
xfer f21 b21
xfer f23 b23
xfer f25 b25
xfer f27 b27
xfer f29 b29
xfer f31 b31
rack 2
xfer f33 b31
xfer f35 b33
xfer f37 b35
xfer f39 b37
rack 0
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit + f36 1
knit - b37 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
knit - b17 1
knit - b15 1
xfer b1 f1
xfer b3 f3
xfer b5 f5
xfer b7 f7
xfer b9 f9
xfer b11 f11
xfer b13 f13
xfer b15 f15
xfer b17 f17
xfer b19 f19
xfer b21 f21
xfer b23 f23
xfer b25 f25
xfer b27 f27
xfer b29 f29
xfer b31 f31
xfer b33 f33
xfer b35 f35
xfer b37 f37
xfer f1 b1
xfer f3 b3
xfer f5 b5
xfer f7 b7
xfer f9 b9
xfer f11 b11
xfer f13 b13
xfer f15 b15
xfer f17 b17
xfer f19 b19
xfer f21 b21
xfer f23 b23
xfer f25 b25
xfer f27 b27
xfer f29 b29
xfer f31 b31
xfer f33 b33
xfer f35 b35
xfer f37 b37
xfer f0 b0
xfer f2 b2
xfer f4 b4
xfer f6 b6
xfer f8 b8
xfer f10 b10
xfer f12 b12
xfer f14 b14
xfer f16 b16
xfer f18 b18
xfer f20 b20
xfer f22 b22
xfer f24 b24
xfer f26 b26
xfer f28 b28
xfer f30 b30
xfer f32 b32
xfer f34 b34
xfer f36 b36
xfer b0 f0
xfer b2 f2
xfer b4 f4
xfer b6 f6
xfer b8 f8
rack -2
xfer b10 f8
xfer b12 f10
xfer b14 f12
xfer b16 f14
xfer b18 f16
xfer b20 f18
xfer b22 f20
xfer b24 f22
xfer b26 f24
xfer b28 f26
xfer b30 f28
xfer b32 f30
xfer b34 f32
xfer b36 f34
rack -1
xfer b37 f36
rack 0
xfer f0 b0
xfer f2 b2
xfer f4 b4
xfer f6 b6
xfer f8 b8
xfer f10 b10
rack 2
xfer f12 b10
xfer f14 b12
xfer f16 b14
xfer f18 b16
xfer f20 b18
xfer f22 b20
xfer f24 b22
xfer f26 b24
xfer f28 b26
xfer f30 b28
xfer f32 b30
xfer f34 b32
xfer f36 b34
rack 0
xfer b0 f0
xfer b2 f2
xfer b4 f4
xfer b6 f6
xfer b8 f8
xfer b10 f10
xfer b12 f12
xfer b14 f14
xfer b16 f16
xfer b18 f18
xfer b20 f20
xfer b22 f22
xfer b24 f24
xfer b26 f26
xfer b28 f28
xfer b30 f30
xfer b32 f32
xfer b34 f34
xfer b1 f1
xfer b3 f3
xfer b5 f5
xfer b7 f7
xfer b9 f9
xfer b11 f11
xfer b13 f13
xfer b15 f15
xfer b17 f17
xfer b19 f19
xfer b21 f21
xfer b23 f23
xfer b25 f25
xfer b27 f27
xfer b29 f29
xfer b31 f31
xfer b33 f33
xfer b35 f35
xfer f1 b1
xfer f3 b3
xfer f5 b5
xfer f7 b7
xfer f9 b9
xfer f11 b11
xfer f13 b13
xfer f15 b15
xfer f17 b17
xfer f19 b19
xfer f21 b21
xfer f23 b23
xfer f25 b25
xfer f27 b27
xfer f29 b29
xfer f31 b31
xfer f33 b33
xfer f35 b35
rack 0
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
knit - b17 1
knit - b15 1
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
xfer f20 b20
xfer f24 b24
xfer f28 b28
xfer f32 b32
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + b20 1
knit + f22 1
knit + b24 1
knit + f26 1
knit + b28 1
knit + f30 1
knit + b32 1
knit + f34 1
xfer b20 f20
xfer b24 f24
xfer b28 f28
xfer b32 f32
xfer b35 f35
xfer b31 f31
xfer b27 f27
xfer b23 f23
xfer b19 f19
xfer b15 f15
knit - f35 1
knit - b33 1
knit - f31 1
knit - b29 1
knit - f27 1
knit - b25 1
knit - f23 1
knit - b21 1
knit - f19 1
knit - b17 1
knit - f15 1
xfer f35 b35
xfer f31 b31
xfer f27 b27
xfer f23 b23
xfer f19 b19
xfer f15 b15
xfer b11 f11
xfer b7 f7
xfer b3 f3
knit - b13 1
knit - f11 1
knit - b9 1
knit - f7 1
knit - b5 1
knit - f3 1
knit - b1 1
xfer f11 b11
xfer f7 b7
xfer f3 b3
xfer f0 b0
xfer f4 b4
xfer f8 b8
xfer f12 b12
xfer f16 b16
xfer f20 b20
xfer f24 b24
xfer f28 b28
xfer f32 b32
knit + b0 1
knit + f2 1
knit + b4 1
knit + f6 1
knit + b8 1
knit + f10 1
knit + b12 1
knit + f14 1
knit + b16 1
knit + f18 1
knit + b20 1
knit + f22 1
knit + b24 1
knit + f26 1
knit + b28 1
knit + f30 1
knit + b32 1
knit + f34 1
xfer b0 f0
xfer b4 f4
xfer b8 f8
xfer b12 f12
xfer b16 f16
xfer b20 f20
xfer b24 f24
xfer b28 f28
xfer b32 f32
xfer b35 f35
xfer b31 f31
xfer b27 f27
xfer b23 f23
xfer b19 f19
xfer b15 f15
knit - f35 1
knit - b33 1
knit - f31 1
knit - b29 1
knit - f27 1
knit - b25 1
knit - f23 1
knit - b21 1
knit - f19 1
knit - b17 1
knit - f15 1
xfer f35 b35
xfer f31 b31
xfer f27 b27
xfer f23 b23
xfer f19 b19
xfer f15 b15
xfer b11 f11
xfer b7 f7
xfer b3 f3
knit - b13 1
knit - f11 1
knit - b9 1
knit - f7 1
knit - b5 1
knit - f3 1
knit - b1 1
xfer f11 b11
xfer f7 b7
xfer f3 b3
xfer f0 b0
xfer f4 b4
xfer f8 b8
xfer f12 b12
xfer f16 b16
xfer f20 b20
xfer f24 b24
xfer f28 b28
xfer f32 b32
knit + b0 1
knit + f2 1
knit + b4 1
knit + f6 1
knit + b8 1
knit + f10 1
knit + b12 1
knit + f14 1
knit + b16 1
knit + f18 1
knit + b20 1
knit + f22 1
knit + b24 1
knit + f26 1
knit + b28 1
knit + f30 1
knit + b32 1
knit + f34 1
xfer b0 f0
xfer b4 f4
xfer b8 f8
xfer b12 f12
xfer b16 f16
xfer b20 f20
xfer b24 f24
xfer b28 f28
xfer b32 f32
xfer b35 f35
xfer b31 f31
xfer b27 f27
xfer b23 f23
xfer b19 f19
xfer b15 f15
knit - f35 1
knit - b33 1
knit - f31 1
knit - b29 1
knit - f27 1
knit - b25 1
knit - f23 1
knit - b21 1
knit - f19 1
knit - b17 1
knit - f15 1
xfer f35 b35
xfer f31 b31
xfer f27 b27
xfer f23 b23
xfer f19 b19
xfer f15 b15
xfer b11 f11
xfer b7 f7
xfer b3 f3
knit - b13 1
knit - f11 1
knit - b9 1
knit - f7 1
knit - b5 1
knit - f3 1
knit - b1 1
xfer f11 b11
xfer f7 b7
xfer f3 b3
xfer f0 b0
xfer f4 b4
xfer f8 b8
xfer f12 b12
xfer f16 b16
knit + b0 1
knit + f2 1
knit + b4 1
knit + f6 1
knit + b8 1
knit + f10 1
knit + b12 1
knit + f14 1
knit + b16 1
knit + f18 1
xfer b0 f0
xfer b4 f4
xfer b8 f8
xfer b12 f12
xfer b16 f16
x-stitch-number 67
knit + f20 1
knit + f24 1
knit + f28 1
knit + f32 1
knit - b35 1
knit - b31 1
knit - b27 1
knit - b23 1
knit - b19 1
knit - b15 1
knit - b11 1
knit - b7 1
knit - b3 1
knit + f0 1
knit + f4 1
knit + f8 1
knit + f12 1
knit + f16 1
knit + f22 1
knit + f26 1
knit + f30 1
knit + f34 1
knit - b33 1
knit - b29 1
knit - b25 1
knit - b21 1
knit - b17 1
knit - b13 1
knit - b9 1
knit - b5 1
knit - b1 1
knit + f2 1
knit + f6 1
knit + f10 1
knit + f14 1
knit + f18 1
x-stitch-number 78
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
knit - b17 1
knit - b15 1
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
knit - b17 1
knit - b15 1
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
knit - b17 1
knit - b15 1
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
knit - b17 1
knit - b15 1
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
knit - b17 1
knit - b15 1
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
knit - b17 1
knit - b15 1
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
knit - b17 1
knit - b15 1
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
knit - b17 1
knit - b15 1
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
knit - b17 1
knit - b15 1
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit - b35 1
knit - b33 1
knit - b31 1
knit - b29 1
knit - b27 1
knit - b25 1
knit - b23 1
knit - b21 1
knit - b19 1
knit - b17 1
knit - b15 1
knit - b13 1
knit - b11 1
knit - b9 1
knit - b7 1
knit - b5 1
knit - b3 1
knit - b1 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
outhook 1
drop f20
drop f22
drop f24
drop f26
drop f28
drop f30
drop f32
drop f34
drop b35
drop b33
drop b31
drop b29
drop b27
drop b25
drop b23
drop b21
drop b19
drop b17
drop b15
drop b13
drop b11
drop b9
drop b7
drop b5
drop b3
drop b1
drop f0
drop f2
drop f4
drop f6
drop f8
drop f10
drop f12
drop f14
drop f16
drop f18
