;!knitout-2
;;Carriers: 1 2 3 4 5 6 7 8 9 10
;;Machine: SWG091N2
;;Gauge: 5
;;Width: 250
;;Position: Center
inhook 2
tuck - f20 2
tuck - f18 2
tuck - f16 2
tuck - f14 2
tuck - f12 2
tuck - f10 2
tuck - f8 2
tuck - f6 2
tuck - f4 2
tuck - f2 2
tuck + f1 2
tuck + f3 2
tuck + f5 2
tuck + f7 2
tuck + f9 2
tuck + f11 2
tuck + f13 2
tuck + f15 2
tuck + f17 2
tuck + f19 2
releasehook 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f17 b17
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f8 b8
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f2 b2
xfer f1 b1
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f17 b17
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f8 b8
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f2 b2
xfer f1 b1
knit - b20 2
knit - b19 2
knit - b18 2
knit - b17 2
knit - b16 2
knit - b15 2
knit - b14 2
knit - b13 2
knit - b12 2
knit - b11 2
knit - b10 2
knit - b9 2
knit - b8 2
knit - b7 2
knit - b6 2
knit - b5 2
knit - b4 2
knit - b3 2
knit - b2 2
knit - b1 2
knit + b1 2
knit + b2 2
knit + b3 2
knit + b4 2
knit + b5 2
knit + b6 2
knit + b7 2
knit + b8 2
knit + b9 2
knit + b10 2
knit + b11 2
knit + b12 2
knit + b13 2
knit + b14 2
knit + b15 2
knit + b16 2
knit + b17 2
knit + b18 2
knit + b19 2
knit + b20 2
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f17 b17
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f8 b8
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f2 b2
xfer f1 b1
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f17 b17
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f8 b8
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f2 b2
xfer f1 b1
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f17 b17
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f8 b8
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f2 b2
xfer f1 b1
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f17 b17
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f8 b8
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f2 b2
xfer f1 b1
knit - b20 2
knit - b19 2
knit - b18 2
knit - b17 2
knit - b16 2
knit - b15 2
knit - b14 2
knit - b13 2
knit - b12 2
knit - b11 2
knit - b10 2
knit - b9 2
knit - b8 2
knit - b7 2
knit - b6 2
knit - b5 2
knit - b4 2
knit - b3 2
knit - b2 2
knit - b1 2
knit + b1 2
knit + b2 2
knit + b3 2
knit + b4 2
knit + b5 2
knit + b6 2
knit + b7 2
knit + b8 2
knit + b9 2
knit + b10 2
knit + b11 2
knit + b12 2
knit + b13 2
knit + b14 2
knit + b15 2
knit + b16 2
knit + b17 2
knit + b18 2
knit + b19 2
knit + b20 2
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f17 b17
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f8 b8
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f2 b2
xfer f1 b1
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f17 b17
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f8 b8
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f2 b2
xfer f1 b1
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f17 b17
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f8 b8
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f2 b2
xfer f1 b1
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f17 b17
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f8 b8
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f2 b2
xfer f1 b1
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f17 b17
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f8 b8
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f2 b2
xfer f1 b1
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f17 b17
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f8 b8
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f2 b2
xfer f1 b1
knit - b20 2
knit - b19 2
knit - b18 2
knit - b17 2
knit - b16 2
knit - b15 2
knit - b14 2
knit - b13 2
knit - b12 2
knit - b11 2
knit - b10 2
knit - b9 2
knit - b8 2
knit - b7 2
knit - b6 2
knit - b5 2
knit - b4 2
knit - b3 2
knit - b2 2
knit - b1 2
knit + b1 2
knit + b2 2
knit + b3 2
knit + b4 2
knit + b5 2
knit + b6 2
knit + b7 2
knit + b8 2
knit + b9 2
knit + b10 2
knit + b11 2
knit + b12 2
knit + b13 2
knit + b14 2
knit + b15 2
knit + b16 2
knit + b17 2
knit + b18 2
knit + b19 2
knit + b20 2
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f17 b17
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f8 b8
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f2 b2
xfer f1 b1
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f17 b17
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f8 b8
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f2 b2
xfer f1 b1
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f17 b17
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f8 b8
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f2 b2
xfer f1 b1
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f17 b17
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f8 b8
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f2 b2
xfer f1 b1
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f17 b17
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f8 b8
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f2 b2
xfer f1 b1
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f17 b17
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f8 b8
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f2 b2
xfer f1 b1
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f17 b17
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f8 b8
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f2 b2
xfer f1 b1
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f17 b17
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f8 b8
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f2 b2
xfer f1 b1
knit - b20 2
knit - b19 2
knit - b18 2
knit - b17 2
knit - b16 2
knit - b15 2
knit - b14 2
knit - b13 2
knit - b12 2
knit - b11 2
knit - b10 2
knit - b9 2
knit - b8 2
knit - b7 2
knit - b6 2
knit - b5 2
knit - b4 2
knit - b3 2
knit - b2 2
knit - b1 2
knit + b1 2
knit + b2 2
knit + b3 2
knit + b4 2
knit + b5 2
knit + b6 2
knit + b7 2
knit + b8 2
knit + b9 2
knit + b10 2
knit + b11 2
knit + b12 2
knit + b13 2
knit + b14 2
knit + b15 2
knit + b16 2
knit + b17 2
knit + b18 2
knit + b19 2
knit + b20 2
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f17 b17
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f8 b8
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f2 b2
xfer f1 b1
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f17 b17
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f8 b8
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f2 b2
xfer f1 b1
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f17 b17
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f8 b8
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f2 b2
xfer f1 b1
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f17 b17
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f8 b8
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f2 b2
xfer f1 b1
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f17 b17
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f8 b8
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f2 b2
xfer f1 b1
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f17 b17
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f8 b8
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f2 b2
xfer f1 b1
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f17 b17
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f8 b8
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f2 b2
xfer f1 b1
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f17 b17
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f8 b8
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f2 b2
xfer f1 b1
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f17 b17
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f8 b8
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f2 b2
xfer f1 b1
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f17 b17
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f8 b8
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f2 b2
xfer f1 b1
knit - b20 2
knit - b19 2
knit - b18 2
knit - b17 2
knit - b16 2
knit - b15 2
knit - b14 2
knit - b13 2
knit - b12 2
knit - b11 2
knit - b10 2
knit - b9 2
knit - b8 2
knit - b7 2
knit - b6 2
knit - b5 2
knit - b4 2
knit - b3 2
knit - b2 2
knit - b1 2
knit + b1 2
knit + b2 2
knit + b3 2
knit + b4 2
knit + b5 2
knit + b6 2
knit + b7 2
knit + b8 2
knit + b9 2
knit + b10 2
knit + b11 2
knit + b12 2
knit + b13 2
knit + b14 2
knit + b15 2
knit + b16 2
knit + b17 2
knit + b18 2
knit + b19 2
knit + b20 2
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b8 f8
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b17 f17
xfer b18 f18
xfer b19 f19
xfer b20 f20
outhook 2
